version: '3.9'
services:
  db:
    image: mysql
    container_name: db-vtr
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: .
    image: backend-vtr:latest
    container_name: backend
    restart: always
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    networks:
      - backend-network
    depends_on:
      db:
        condition: service_healthy
networks:
  backend-network:
    driver: bridge
