version: '3.9'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  backend:
    build: .
    image: backend-vtr:latest
    container_name: backend
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db